services:
  eurekaserver:
    build: ./eurekaserver
    container_name: eurekaserver
    ports:
      - "8761:8761"
    healthcheck:
      test: "curl --fail --silent localhost:8761/actuator/health | grep UP || exit 1"
      interval: 10s

  configserver:
    build: ./configserver
    container_name: configserver
    ports:
      - "9999:9999"
    healthcheck:
      test: "curl --fail --silent localhost:9999/actuator/health | grep UP || exit 1"
      interval: 10s

  championnat-ms:
    build: ./championnat-microservice
    container_name: championnat-ms
    ports:
      - "8090:8080"
    environment:
      - DISCOVERY_SERVICE_URL=http://eurekaserver:8761/eureka
      - CONFIG_SERVICE_URL=http://configserver:9999
    healthcheck:
      test: "curl --fail --silent localhost:8090/actuator/health | grep UP || exit 1"
    depends_on:
      eurekaserver:
        condition: service_healthy
      configserver:
        condition: service_healthy

  gatewayserver:
    build: ./gatewayserver
    container_name: gatewayserver
    ports:
      - "8888:8888"
    environment:
      - DISCOVERY_SERVICE_URL=http://eurekaserver:8761/eureka
      - CONFIG_SERVICE_URL=http://configserver:9999
    healthcheck:
      test: "curl --fail --silent localhost:8888/actuator/health | grep UP || exit 1"
    depends_on:
      eurekaserver:
        condition: service_healthy
      configserver:
        condition: service_healthy

  championnat-ms2:
    build: ./championnat-microservice
    container_name: championnat-ms2
    ports:
      - "8091:8080"
    environment:
      - DISCOVERY_SERVICE_URL=http://eurekaserver:8761/eureka
      - CONFIG_SERVICE_URL=http://configserver:9999
    healthcheck:
      test: "curl --fail --silent localhost:8091/actuator/health | grep UP || exit 1"
    depends_on:
      eurekaserver:
        condition: service_healthy
      configserver:
        condition: service_healthy

  driver-ms:
    build: ./driver-microservice
    container_name: driver-ms
    ports:
      - "8889:8889"
    environment:
      - DISCOVERY_SERVICE_URL=http://eurekaserver:8761/eureka
      - CONFIG_SERVICE_URL=http://configserver:9999
    healthcheck:
      test: "curl --fail --silent localhost:8889/actuator/health | grep UP || exit 1"
    depends_on:
      eurekaserver:
        condition: service_healthy
      configserver:
        condition: service_healthy
      championnat-ms:
        condition: service_healthy