spring:
#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"
  profiles:
    active: "prod"
  config:
    import: "optional:configserver:http://localhost:9999/"

  application:
    name: championnat-microservice
  datasource:
    url: 'jdbc:h2:mem:depdb'
  h2:
    console:
      enabled: true
#    url: jdbc:mysql://mysqldb:3306/test?useSSL=false&serverTimezone=UTC
#    username: root
#    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  cloud:
    config:
      enabled: true
    discovery:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
    hostname: localhost

server:
  port: 8890

management:
  endpoints:
    web:
      exposure:
        include: '*'
build:
  version : "1.0"
author:
  name: "moetez maaoui"
  email: "moetezmaaoui0@gmail.com"

